#!/usr/bin/env node
// Generates German word-pronunciation audio using Microsoft Edge's free neural
// TTS voices (via `msedge-tts` — the same voices behind Edge's "Read Aloud"
// feature, no API key or account needed).
//
// Usage:
//   bun run generate-audio           generate only missing files
//   bun run generate-audio -- --force  regenerate every file
//
// To add a new word: add an entry to WORDS below, then rerun this script.
// It writes small mp3s to public/audio/ and regenerates the manifest at
// src/data/word-audio.generated.ts that the app imports at runtime.

import { MsEdgeTTS, OUTPUT_FORMAT } from "msedge-tts";
import { mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const AUDIO_DIR = path.join(ROOT, "public", "audio");
const MANIFEST_PATH = path.join(ROOT, "src", "data", "word-audio.generated.ts");

const VOICE = "de-DE-KatjaNeural"; // friendly female voice, good for kids
const RATE = "-15%"; // slightly slower than natural speech, easier for beginners

// word: what gets spoken (including the article, since kids need to learn it).
// slug: the mp3 filename, also used as the word's stable id.
const WORDS = [
  { word: "der Hund", slug: "hund" },
  { word: "die Katze", slug: "katze" },
  { word: "der Vogel", slug: "vogel" },
  { word: "das Pferd", slug: "pferd" },
  { word: "der Apfel", slug: "apfel" },
  { word: "die Banane", slug: "banane" },
  { word: "das Buch", slug: "buch" },
  { word: "das Wasser", slug: "wasser" },
];

const force = process.argv.includes("--force");

await mkdir(AUDIO_DIR, { recursive: true });

for (const { word, slug } of WORDS) {
  const filePath = path.join(AUDIO_DIR, `${slug}.mp3`);
  if (existsSync(filePath) && !force) {
    console.log(`skip   ${slug}.mp3 (already exists, use --force to regenerate)`);
    continue;
  }

  const tts = new MsEdgeTTS();
  await tts.setMetadata(VOICE, OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);
  const { audioStream } = tts.toStream(word, { rate: RATE });

  const chunks = [];
  for await (const chunk of audioStream) chunks.push(chunk);
  const buffer = Buffer.concat(chunks);
  await writeFile(filePath, buffer);
  console.log(`wrote  ${slug}.mp3 (${buffer.length} bytes) — "${word}"`);
}

const manifestBody = WORDS.map(({ word, slug }) => `  ${JSON.stringify(word)}: "/audio/${slug}.mp3",`).join("\n");
const manifest = `// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Maps a full German word (with article) to its pronunciation audio file.
export const WORD_AUDIO: Record<string, string> = {
${manifestBody}
};
`;

await mkdir(path.dirname(MANIFEST_PATH), { recursive: true });
await writeFile(MANIFEST_PATH, manifest);
console.log(`wrote  ${path.relative(ROOT, MANIFEST_PATH)}`);
