// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Maps a full German word (with article) or lesson-screen title to its
// pronunciation audio file.
export const WORD_AUDIO: Record<string, string> = {
  "der Hund": "/audio/hund.mp3",
  "die Katze": "/audio/katze.mp3",
  "der Vogel": "/audio/vogel.mp3",
  "das Pferd": "/audio/pferd.mp3",
  "der Apfel": "/audio/apfel.mp3",
  "die Banane": "/audio/banane.mp3",
  "das Buch": "/audio/buch.mp3",
  "das Wasser": "/audio/wasser.mp3",
  "der": "/audio/article-der.mp3",
  "die": "/audio/article-die.mp3",
  "das": "/audio/article-das.mp3",
  "Was ist das?": "/audio/title-was-ist-das.mp3",
  "Welches Bild ist das?": "/audio/title-welches-bild-ist-das.mp3",
  "Was bedeutet das?": "/audio/title-was-bedeutet-das.mp3",
  "Wie sagt man das auf Deutsch?": "/audio/title-wie-sagt-man-das-auf-deutsch.mp3",
  "Welcher Artikel passt?": "/audio/title-welcher-artikel-passt.mp3",
  "Baue das Wort": "/audio/title-baue-das-wort.mp3",
  "Welcher Buchstabe fehlt?": "/audio/title-welcher-buchstabe-fehlt.mp3",
  "Ordne die Buchstaben": "/audio/title-ordne-die-buchstaben.mp3",
  "Was hörst du?": "/audio/title-was-hoerst-du.mp3",
  "Welches Bild hörst du?": "/audio/title-welches-bild-hoerst-du.mp3",
  "Finde die Paare": "/audio/title-finde-die-paare.mp3",
};
