// AUTO-GENERATED by scripts/generate-audio.mjs — do not edit by hand.
// Maps a full German word (with article) to its pronunciation audio file.
export const WORD_AUDIO: Record<string, string> = {
  "der Hund": "/audio/hund.mp3",
  "die Katze": "/audio/katze.mp3",
  "der Vogel": "/audio/vogel.mp3",
  "das Pferd": "/audio/pferd.mp3",
  "der Apfel": "/audio/apfel.mp3",
  "die Banane": "/audio/banane.mp3",
  "das Buch": "/audio/buch.mp3",
  "das Wasser": "/audio/wasser.mp3",
};
